service: productservice
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '3'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-auto-swagger

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2

functions:
  getProductsList:
    handler: ./handlers/getProductsList.handler
    events:
      - httpApi:
          method: get
          path: /products

  getProductsById:
    handler: ./handlers/getProductsById.handler
    events:
      - httpApi:
          method: get
          path: /products/{productId}
